name: Docker Image CI

on:
  push:
    branches: 
       - master
  pull_request:
    branches: 
      - master       
env:
  IMAGE_NAME: step1

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Docker Action
        uses: zenato/docker-action@v1.0.0
        with:
            # Registry username
            username: ${{ secrets.DOCKER_USERNAME }}
            # Registry password
            password: ${{ secrets.DOCKER_PASSWORD }}
            # Repository on registry
            repository: ${{ secrets.DOCKER_REPOSITORY_NAME }}
            # Registry hostname
            registry: ${{ secrets.DOCKER_REGISTRY_URL }}
            # Image tag
            tag: latest
